repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 5.0.1
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/myint/autoflake
    rev: v1.5.7
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--remove-unused-variables", "--in-place"]
        language_version: python3
